

services:
  backend:
    build:
      context: ./backend
      
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
